version: '3.3'

networks:
  codechat-net:
    driver: bridge

services:
  base:
    container_name: codechat_api
    image: codechat/api:local
    ports:
      - 8083:8083
    volumes:
      - /data/instances:/codechat/instances
    command: ['node', './dist/src/main.js']

    networks:
      - codechat-net
