version: '3.8'

networks:
  api-net:
    driver: bridge

services:
  codechatapi:
    container_name: api_codechat
    build:
      context: .
      dockerfile: ./Dockerfile
    image: whatsappapi/codechat:latest

    ports:
      - 8080:8080

    command: npm run start:prod

    networks:
      - api-net
