version: '3.3'

networks:
  public-network:
    driver: bridge

services:
  api:
    container_name: codechat_api
    image: codechat/api:v1.2.6
    restart: unless-stopped
    ports:
      - 8084:8083
    volumes:
      - instances_connecteds:/codechat/instances
    environment:
      - SERVER_PORT=8083
      - SESSION_SECRET=W0NvZGVDaGF0XTpbU2Vzc

      - LOG_LEVEL=ERROR|WARN|INFO|DEBUG|LOG|VERBOSE|DARK
      - LOG_COLOR=true

      - DATABASE_ENABLED=true
      - DATABASE_URL=postgres://<USER>:<PASS>@<HOST>/codechat_api_v1
      - DATABASE_SYNC_MESSAGES=true
      - DATABASE_SAVE_DATA_NEW_MESSAGE=true
      - DATABASE_SAVE_MESSAGE_UPDATE=true
      - DATABASE_SAVE_DATA_CONTACTS=true
      - DATABASE_SAVE_DATA_CHATS=true

      - GLOBAL_WEBHOOK_URL=url
      - GLOBAL_WEBHOOK_ENABLED=false

      - INSTANCE_EXPIRATION_TIME=false

      - CONFIG_SESSION_PHONE_CLIENT=CodeChat_V1
      - CONFIG_SESSION_PHONE_NAME=Edge

      - QRCODE_LIMIT=10
      - QRCODE_EXPIRATION_TIME=60

      - CONNECTION_TIMEOUT=300

      - AUTHENTICATION_GLOBAL_AUTH_TOKEN=zYzP7ocstxh3SJ23D4FZTCu4ehnM8v4hu
      - AUTHENTICATION_JWT_EXPIRES_IN=0
      - AUTHENTICATION_JWT_SECRET=3RFYiiRmvNiokSBrLZzx

      - REDIS_ENABLED=true
      - REDIS_URI=redis://data.srv.codechat.com.br/5
      - REDIS_PREFIX=codechat

      - S3_ENABLED=true
      - S3_ACCESS_KEY=XCXV6CawqzpOTlpGmZC2
      - S3_SECRET_KEY=CEU2tqUv2VDsy1a3vNiQWfb16kW7UzLZ6Dg3hfSr
      - S3_BUCKET=codechat-api-v1
      - S3_PORT=443
      - S3_ENDPOINT=s3.codechat.com.br
      - S3_USE_SSL=true
    networks:
      - public-network
    depends_on:
      - postgres_server

  postgres_server:
    image: postgres:latest
    container_name: postgres_server
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - public_network
  
  redis_cache:
    image: redis:latest
    container_name: redis_cache
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - public_network

volumes:
  instances_connecteds:
    driver: local
  postgres_data:
    driver: local
  redis_data:
    driver: local

