name: Solicitação de recursos (Traefik)
description: Sugira ideisas para o projeto.
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Bem-vindo!
      description: NÃO ABRA PARA PERGUNTAS GERAIS DE SUPORTE.

      options:
        - label: Sim, pesquisei problemas semelhantes no [GitHub](https://github.com/code-chat-br/whatsapp-api/issues) e não encontrei nenhum.
          required: true

  - type: dropdown
    attributes:
      label: Qual tipo de recurso?
      description: |
        Como escrever uma boa solicitação de bug?

        - Respeite o modelo de problema tanto quanto possível.
        - O título deve ser curto e descritivo.
        - Explique as condições que o levaram a reportar este problema: o contexto.
        - O contexto deve levar a algo, ideia ou problema que você está enfrentando.
        - Seja claro e conciso.
        - Formate suas mensagens para ajudar o leitor a se concentrar no que importa e entender a estrutura da sua mensagem, use [sintaxe Markdown](https://help.github.com/articles/github-flavored-markdown)
      options:
        - Integração
        - Funcionalidade
        - Endpoint
        - Ajuste de banco de dados
        - Outro
    validations:
      required: true

  - type: textarea
    attributes:
      label: Qual a motivação para a solicitação?
      description: Qual problema o recurso busca resolver?
      placeholder: Descreva a motivação para o recurso
    validations:
      required: true

  - type: textarea
    attributes:
      label: Como o recurso deve ser desenvolvido?
      description: |
        Deve ser inserido diretamente no código?
        Deve ser construído uma aplicação diferente que atuará como uma extenção da api? Um `worker`
      placeholder: Insira ideias para o recurso
    validations:
      required: true

  - type: textarea
    attributes:
      label: Pode ser construído com o n8n?
      description: |
        Quais nós podem ser usados?
        Descreva o fluxo.
      placeholder: Insira ideias para o recurso
    validations:
      required: false