
version: '3.8'

networks:
  mongo-net:
    driver: bridge

services:
  mongodb:
    container_name: mongodb

    # This image already has a single replica set
    image: bitnami/mongodb:latest

    restart: always
    volumes:
      # sudo mkdir -p /data/mongodb
      - /data/mongodb:/data/db
    ports:
      - 26712:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=root
      # Set a password to access the bank
      - MONGODB_ROOT_PASSWORD=<password>
      - MONGODB_REPLICA_SET_KEY=9glkjQlr855kU
    networks:
      - mongo-net
    expose:
      - 26712
