
version: '3.8'

networks:
  api-net:
    driver: bridge

services:
  mongodb:
    container_name: mongodb

    # This image already has a single replica set
    image: mongo

    restart: always
    volumes:
      # sudo mkdir -p /data/mongodb
      - /data/mongodb:/data/db
    ports:
      - 26712:27017
    environment:
      - MONGODB_ROOT_USER=root
      # Set a password to access the bank
      - MONGODB_ROOT_PASSWORD=<password>
    networks:
      - api-net
    expose:
      - 26712
