version: '3.3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_server
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongodb_data:/data/db
    ports:
      - "11270:27017"
    networks:
      - public_network

networks:
  public_network:
    external: true

volumes:
  mongodb_data:
